name: WebApp Demo
'on':
  push:
    branches:
      - main
      - dev
env:
  IMAGE_NAME_main: mbwebapp-main
  IMAGE_NAME_dev: mbwebapp-dev
jobs:
  build-main:
    name: Build-main
    runs-on:
      - ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login into registry
        uses: docker/login-action@v2
        with:
          registry: '${{ secrets.AZURE_ACR_ENDPOINT }}'
          username: '${{ secrets.AZURE_CLIENT_ID }}'
          password: '${{ secrets.AZURE_CLIENT_SECRET }}'
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: >
            ${{ secrets.AZURE_ACR_ENDPOINT }}/${{ env.IMAGE_NAME_main }}:${{
            github.sha }}

            ${{ secrets.AZURE_ACR_ENDPOINT }}/${{ env.IMAGE_NAME_main }}:latest
            build-args:
            FLASK_OUTPUT_DIR:/home
  build-dev:
    name: Build-dev
    runs-on:
      - ubuntu-latest
    if: github.ref_name == 'dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login into registry
        uses: docker/login-action@v2
        with:
          registry: '${{ secrets.AZURE_ACR_ENDPOINT }}'
          username: '${{ secrets.AZURE_CLIENT_ID }}'
          password: '${{ secrets.AZURE_CLIENT_SECRET }}'
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: >
            ${{ secrets.AZURE_ACR_ENDPOINT }}/${{ env.IMAGE_NAME_dev }}:${{
            github.sha }}

            ${{ secrets.AZURE_ACR_ENDPOINT }}/${{ env.IMAGE_NAME_dev }}:latest
            build-args:
            FLASK_OUTPUT_DIR:/home
